Description of the script usage
uibakery/onpremise pull request #1
Opened 2022-06-14 13:43 UTC by AlexandrStadolnik

Adds description of how to install Bakery using script.

2022-06-14 14:15 UTC, Tibing requested changes

2022-06-14 14:15 UTC, Tibing commented on README.md
> +:warning: The script installs docker and doker-compose, which may upgrade some dependencies under the hood. Please, be advised that if you are running this script on the OS used as a severs for other
The script installs docker and docker-compose, which may upgrade some dependencies under the hood. Please be advised that if you run this script on the OS used as a server for other applications, those applications may break due to that potential dependencies upgrade.

2022-06-14 14:15 UTC, Tibing commented on README.md
> +1. Once the installation is completed, open the browser using URL and provided earlier. By default it is [http://localhost:3030/](http://localhost:3030/).
```suggestion
2. Once the installation is completed, open the browser using the URL provided earlier. By default it is [http://localhost:3030/](http://localhost:3030/).
```

2022-06-14 14:15 UTC, Tibing commented on README.md
> +1. In the process, upon request, enter the previously received license code, hosting URL and port.
```suggestion
1. In the process, upon request, enter the previously received license code, hosting URL and port.
```

2022-06-14 14:52 UTC, AlexandrStadolnik commented on README.md
> +1. In the process, upon request, enter the previously received license code, hosting URL and port.
Says this suggestion is invalid because no changes were made to the code

2022-06-14 15:04 UTC, AlexandrStadolnik commented on README.md
> +1. Once the installation is completed, open the browser using URL and provided earlier. By default it is [http://localhost:3030/](http://localhost:3030/).
Resolved

2022-06-15 10:34 UTC, Tibing approved these changes
<img src="https://media1.giphy.com/media/3oz8xVjxTPNEzyKRKU/giphy.gif"/>

2022-06-15 10:35 UTC, merged